# ASSIGNMENT 2 
**Topic: Chapter 3 & Chapter 4**
- Due: 4th December 2023
- Mode: Group Assignment (Not more than 3 students per group)
- Submission: E-Learning

GROUP NAME : UIA

1.IKMAL BIN KHAIRULEZUAN A21EC0186

2.ALIEYA ZAWANIE BINTI A ZAINI A21EC0156

3.UMAR HAZIQ BIN MUHAMAD NORHISHAM A21EC0235


### QUESTION 1


Given a raw data of the record of the attendance for 15 employees in a company for a 14 days event. The exported raw data is recorded in following way:

<br>
<center>Figure 1</center>
<img src="Figure 1.png", style="width: 350px";>

(i) Read the “Attendance_RAW.txt” and save the data into a NumPy array.

In [1]:
import numpy as np

# Load data from "Attendance_RAW.txt"

file_path = 'Attendance_RAW.txt'

attendance = np.loadtxt(file_path)

print(attendance)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0.
 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0.
 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1.]


(ii) Shape the NumPy array to a structure where row represents the employees, column represents the working days.

In [2]:
# WRITE YOUR CODE HERE

attendance1 = np.reshape(attendance, (15, 14))
print(attendance1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1.]
 [1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1.]]


(iii) Construct a function that can calculate and return the list of average of attendance for each day.

In [3]:
# WRITE YOUR CODE HERE


def avg_daily_attendance(attendance1):
    daily_average = np.mean(attendance1, axis=1)
    return daily_average.tolist()

daily_average_list = avg_daily_attendance(attendance1)
print("Daily Average Attendance:")
print(daily_average_list)



Daily Average Attendance:
[1.0, 0.8571428571428571, 0.7142857142857143, 0.7857142857142857, 0.5, 0.8571428571428571, 0.7142857142857143, 0.6428571428571429, 0.7142857142857143, 0.6428571428571429, 0.7857142857142857, 0.9285714285714286, 0.7142857142857143, 0.7857142857142857, 0.6428571428571429]


### QUESTION 2

(i) Create a NumPy array like below:

<br>
<img src="Output2.png", style="width: 200px", align="left";>

In [11]:
# WRITE YOUR CODE HERE
import numpy as np


array = np.array([[33, 22, 11],
                  [55, 66, 44],
                  [99, 88, 77]])

array


array([[33, 22, 11],
       [55, 66, 44],
       [99, 88, 77]])

(ii) Sort the array given in ascending order.

In [10]:
# WRITE YOUR CODE HERE

sortarray = np.sort(array,axis=1)
sortarray



array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

(iii) Compute sum of all elements, sum of each column and sum of each row of the sorted array.

In [9]:
# WRITE YOUR CODE HERE
total_sum_elements = np.sum(sortarray)
column_sums = np.sum(sortarray, axis=0)
row_sums = np.sum(sortarray, axis=1)

print("Sum of all elements:", total_sum_elements)
print("Sum of each column:",column_sums)
print("Sum of each row:", row_sums)

Sum of all elements: 495
Sum of each column: [132 165 198]
Sum of each row: [ 66 165 264]


(iv) Compute mean of all elements, mean of each column and mean of each row of the sorted array.



In [8]:
# WRITE YOUR CODE HERE
mean_elements = np.mean(sortarray)
column_mean = np.mean(sortarray, axis=0)
row_mean = np.mean(sortarray, axis=1)

print("Mean of all elements:", mean_elements)
print("Mean of each column:", column_mean)
print("Mean of each row:",row_mean )


Mean of all elements: 55.0
Mean of each column: [44. 55. 66.]
Mean of each row: [22. 55. 88.]


(v) Compute cumulative sum of each column and cumulative product of each row of the given array.


In [7]:
# WRITE YOUR CODE HERE
ccs = np.cumsum(sortarray, axis=0)
crp = np.cumprod(sortarray, axis=1)

print("Cumulative Column Sum:")
print(ccs)

print("\nCumulative Row Product:")
print(crp)


Cumulative Column Sum:
[[ 11  22  33]
 [ 55  77  99]
 [132 165 198]]

Cumulative Row Product:
[[    11    242   7986]
 [    44   2420 159720]
 [    77   6776 670824]]


### QUESTION 3
For this question, you are using Automobile Dataset. 

(i) Load the dataset into pandas dataframe.

In [2]:
# WRITE YOUR CODE HERE
import pandas as pd
import numpy as np

automobile_dataset = pd.read_csv("Automobile Dataset.csv")
automobile_dataset


index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four         111               21  16500.0  
2               six         154               19  16500.0  
3              four         102               24  13950.0  
4              five         115               18  17450.0  
..              ...         ...              ...      ...  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0  

[61 rows x 10 columns]

(ii) Display the first and last 5 rows.

In [3]:
# WRITE YOUR CODE HERE (for the first 5 rows)
automobile_dataset.head(5)


index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

In [4]:
# WRITE YOUR CODE HERE (for the last 5 rows)
automobile_dataset.tail(5)


index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

(iii) Print most expensive car’s company name and price.

In [14]:
# WRITE YOUR CODE HERE
max_price = automobile_dataset['price'].max()

company_name = automobile_dataset.loc[automobile_dataset['price'] == max_price, 'company'].iloc[0]

print(f"The most expensive car is from {company_name} with a price of {max_price}")



The most expensive car is from mercedes-benz with a price of 45400.0


(iv) Count total cars per company.

In [17]:
# WRITE YOUR CODE HERE

cars_per_company = automobile_dataset['company'].value_counts(ascending=False)

print(cars_per_company)


company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64


(v) Select only Toyota's cars. Find the average mileage and price of Toyota's cars.

In [20]:
# WRITE YOUR CODE HERE
Toyota_only_dataset = automobile_dataset.loc [automobile_dataset ['company'] == 'toyota']

Toyota_avgMile_Price = Toyota_only_dataset[['company', 'average-mileage', 'price']]

Toyota_avgMile_Price

company  average-mileage    price
48  toyota               35   5348.0
49  toyota               31   6338.0
50  toyota               31   6488.0
51  toyota               31   6918.0
52  toyota               27   7898.0
53  toyota               27   8778.0
54  toyota               19  15750.0

(vi) Sort all cars by Price and Horsepower column. List the expensive cars first.

In [4]:
# WRITE YOUR CODE HERE
sorted_cars = automobile_dataset.sort_values(by=['price', 'horsepower'], ascending=[False, False])

print(sorted_cars)


    index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   
..    ...            ...          ...         ...     ...         ...   
27     36          mazda    hatchback        93.1   159.1         ohc   
13     16      chevrolet    hatchback        88.4   141.1           l   
47     63        porsche    hatchback        98.4   175.7       dohcv   
22     31          isuzu        sedan        94.5   155.9         ohc   
23     32          isuzu        sedan        94.5   155.9         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11 

(vii) Display all the maximum car price for each company.

In [9]:
# WRITE YOUR CODE HERE
max_prices_per_company = automobile_dataset.groupby('company')['price'].max()

sorted_max_prices_per_company = max_prices_per_company.sort_values(ascending=False)

sorted_max_prices_per_company 



company
mercedes-benz    45400.0
bmw              41315.0
porsche          37028.0
jaguar           36000.0
audi             18920.0
mazda            18344.0
alfa-romero      16500.0
toyota           15750.0
nissan           13499.0
volvo            13415.0
honda            12945.0
volkswagen        9995.0
mitsubishi        8189.0
isuzu             6785.0
chevrolet         6575.0
dodge             6377.0
Name: price, dtype: float64

### QUESTION 4


Given a data file, “emp_detail.csv” which consists of the employee’s details - name and department.

<br>
<img src="Figure 2.png", style="width: 250px";>

(i) Using Pandas library, read the CSV data file in Python into a variable ``emp_detail``.

In [1]:
# WRITE YOUR CODE HERE

import pandas as pd

emp_detail = pd.read_csv('emp_detail.csv')

print(emp_detail)


       Name Department
0       ALI    FINANCE
1     AHMAD   STAFFING
2     CHONG    FINANCE
3    DARREN   STAFFING
4   JASMINE   STAFFING
5    JOSHUA   STAFFING
6     KELLY    FINANCE
7       LIM    FINANCE
8   NATASHA    FINANCE
9      OMAR   STAFFING
10   PATRIC   STAFFING
11     ROSE   STAFFING
12    SATYA   STAFFING
13    TARIQ   STAFFING
14    USMAN   STAFFING


(ii) Display the first five rows of records of the data read in Step (i).

In [2]:
# WRITE YOUR CODE HERE

print(emp_detail.head())

      Name Department
0      ALI    FINANCE
1    AHMAD   STAFFING
2    CHONG    FINANCE
3   DARREN   STAFFING
4  JASMINE   STAFFING


(iii) Using the NumPy object of the attendance record created earlier:<br>
            a.	Convert the NumPy object into Data Frame, name it attendance.<br>
          

In [19]:
# WRITE YOUR CODE HERE

attendence = pd.DataFrame(attendance1,index = range(0,15), columns = range(1,15))
attendance

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1])

b. Merge the Data Frames emp_detail and attendance into a new data frame, name it emp_attendance.

In [31]:
# WRITE YOUR CODE HERE

emp_details = pd.DataFrame(emp_detail, index = range(0,15))
emp_attendance = emp_details.join(attendence)
emp_attendance

Name Department  1  2  3  4  5  6  7  8  9  10  11  12  13  14
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1   1   1   1   1   1
1     AHMAD   STAFFING  0  1  1  1  1  1  1  1  1   1   0   1   1   1
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0   0   1   1   0   1
3    DARREN   STAFFING  1  0  1  1  0  1  1  1  1   0   1   1   1   1
4   JASMINE   STAFFING  1  0  0  0  1  1  1  1  0   0   0   0   1   1
5    JOSHUA   STAFFING  1  1  1  1  1  1  1  1  0   1   1   1   0   1
6     KELLY    FINANCE  1  1  1  0  0  1  1  1  0   1   1   0   1   1
7       LIM    FINANCE  0  0  1  1  1  1  1  1  1   1   0   0   1   0
8   NATASHA    FINANCE  0  1  1  1  1  0  1  0  1   1   0   1   1   1
9      OMAR   STAFFING  0  1  0  1  0  1  1  1  1   1   1   0   1   0
10   PATRIC   STAFFING  0  0  0  1  1  1  1  1  1   1   1   1   1   1
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1   1   1   1   1   0
12    SATYA   STAFFING  1  1  0  0  0  0  1  1  1   1   1   1   1   1
13    TARIQ   STAFFING  0  0  1  1  1  1  1  1  1   1   1   1   0   1
14    USMAN   STAFFING  1  0  1  1  1  0  0  0  1   0   1   1   1   1

(iv) Add a column with name ``total`` into the ``emp_attendance`` Data Frame that consists of the total no. of days the employee attended the event.

In [44]:
total_attendance = attendance1.sum(axis=1)
emp_attendance = emp_attendance.assign(total = total_attendance)
emp_attendance

Name Department  1  2  3  4  5  6  7  8  9  10  11  12  13  14  total  \
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1   1   1   1   1   1     14   
1     AHMAD   STAFFING  0  1  1  1  1  1  1  1  1   1   0   1   1   1     12   
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0   0   1   1   0   1     10   
3    DARREN   STAFFING  1  0  1  1  0  1  1  1  1   0   1   1   1   1     11   
4   JASMINE   STAFFING  1  0  0  0  1  1  1  1  0   0   0   0   1   1      7   
5    JOSHUA   STAFFING  1  1  1  1  1  1  1  1  0   1   1   1   0   1     12   
6     KELLY    FINANCE  1  1  1  0  0  1  1  1  0   1   1   0   1   1     10   
7       LIM    FINANCE  0  0  1  1  1  1  1  1  1   1   0   0   1   0      9   
8   NATASHA    FINANCE  0  1  1  1  1  0  1  0  1   1   0   1   1   1     10   
9      OMAR   STAFFING  0  1  0  1  0  1  1  1  1   1   1   0   1   0      9   
10   PATRIC   STAFFING  0  0  0  1  1  1  1  1  1   1   1   1   1   1     11   
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1   1   1   1   1   0     13   
12    SATYA   STAFFING  1  1  0  0  0  0  1  1  1   1   1   1   1   1     10   
13    TARIQ   STAFFING  0  0  1  1  1  1  1  1  1   1   1   1   0   1     11   
14    USMAN   STAFFING  1  0  1  1  1  0  0  0  1   0   1   1   1   1      9   

      rate    status  
0   100.00      Good  
1    85.71  Moderate  
2    71.43  Moderate  
3    78.57  Moderate  
4    50.00       Bad  
5    85.71  Moderate  
6    71.43  Moderate  
7    64.29  Moderate  
8    71.43  Moderate  
9    64.29  Moderate  
10   78.57  Moderate  
11   92.86      Good  
12   71.43  Moderate  
13   78.57  Moderate  
14   64.29  Moderate

(v) Add a column with name ``rate`` into the ``emp_attendance`` Data Frame that consists of the attendance rate / percentage the employee throughout the 14 days.

In [45]:
# WRITE YOUR CODE HERE

attendance_rate= attendance1.sum(axis=1)/14 * 100
emp_attendance = emp_attendance.assign(rate = attendance_rate.round(2))
emp_attendance

Name Department  1  2  3  4  5  6  7  8  9  10  11  12  13  14  total  \
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1   1   1   1   1   1     14   
1     AHMAD   STAFFING  0  1  1  1  1  1  1  1  1   1   0   1   1   1     12   
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0   0   1   1   0   1     10   
3    DARREN   STAFFING  1  0  1  1  0  1  1  1  1   0   1   1   1   1     11   
4   JASMINE   STAFFING  1  0  0  0  1  1  1  1  0   0   0   0   1   1      7   
5    JOSHUA   STAFFING  1  1  1  1  1  1  1  1  0   1   1   1   0   1     12   
6     KELLY    FINANCE  1  1  1  0  0  1  1  1  0   1   1   0   1   1     10   
7       LIM    FINANCE  0  0  1  1  1  1  1  1  1   1   0   0   1   0      9   
8   NATASHA    FINANCE  0  1  1  1  1  0  1  0  1   1   0   1   1   1     10   
9      OMAR   STAFFING  0  1  0  1  0  1  1  1  1   1   1   0   1   0      9   
10   PATRIC   STAFFING  0  0  0  1  1  1  1  1  1   1   1   1   1   1     11   
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1   1   1   1   1   0     13   
12    SATYA   STAFFING  1  1  0  0  0  0  1  1  1   1   1   1   1   1     10   
13    TARIQ   STAFFING  0  0  1  1  1  1  1  1  1   1   1   1   0   1     11   
14    USMAN   STAFFING  1  0  1  1  1  0  0  0  1   0   1   1   1   1      9   

      rate    status  
0   100.00      Good  
1    85.71  Moderate  
2    71.43  Moderate  
3    78.57  Moderate  
4    50.00       Bad  
5    85.71  Moderate  
6    71.43  Moderate  
7    64.29  Moderate  
8    71.43  Moderate  
9    64.29  Moderate  
10   78.57  Moderate  
11   92.86      Good  
12   71.43  Moderate  
13   78.57  Moderate  
14   64.29  Moderate

(vi) Consider following rules in classify the attendance:<br>
        a.	Rate > 90% : Good <br>
        b.	60% < Rate < 90% : Moderate <br>
        c.	Rate < 60% : Bad <br>
    Based on the grouping rule above, get the status for each of the staff and save the status in a new column ``status`` in the Data Frame.

In [46]:
# WRITE YOUR CODE HERE

status_attend = []
for i in attendance_rate:
    if i > 90:
        status_attend.append("Good")
    elif i > 60:
        status_attend.append("Moderate")
    else:
        status_attend.append("Bad")

emp_attendance = emp_attendance.assign(status = status_attend)
emp_attendance

Name Department  1  2  3  4  5  6  7  8  9  10  11  12  13  14  total  \
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1   1   1   1   1   1     14   
1     AHMAD   STAFFING  0  1  1  1  1  1  1  1  1   1   0   1   1   1     12   
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0   0   1   1   0   1     10   
3    DARREN   STAFFING  1  0  1  1  0  1  1  1  1   0   1   1   1   1     11   
4   JASMINE   STAFFING  1  0  0  0  1  1  1  1  0   0   0   0   1   1      7   
5    JOSHUA   STAFFING  1  1  1  1  1  1  1  1  0   1   1   1   0   1     12   
6     KELLY    FINANCE  1  1  1  0  0  1  1  1  0   1   1   0   1   1     10   
7       LIM    FINANCE  0  0  1  1  1  1  1  1  1   1   0   0   1   0      9   
8   NATASHA    FINANCE  0  1  1  1  1  0  1  0  1   1   0   1   1   1     10   
9      OMAR   STAFFING  0  1  0  1  0  1  1  1  1   1   1   0   1   0      9   
10   PATRIC   STAFFING  0  0  0  1  1  1  1  1  1   1   1   1   1   1     11   
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1   1   1   1   1   0     13   
12    SATYA   STAFFING  1  1  0  0  0  0  1  1  1   1   1   1   1   1     10   
13    TARIQ   STAFFING  0  0  1  1  1  1  1  1  1   1   1   1   0   1     11   
14    USMAN   STAFFING  1  0  1  1  1  0  0  0  1   0   1   1   1   1      9   

      rate    status  
0   100.00      Good  
1    85.71  Moderate  
2    71.43  Moderate  
3    78.57  Moderate  
4    50.00       Bad  
5    85.71  Moderate  
6    71.43  Moderate  
7    64.29  Moderate  
8    71.43  Moderate  
9    64.29  Moderate  
10   78.57  Moderate  
11   92.86      Good  
12   71.43  Moderate  
13   78.57  Moderate  
14   64.29  Moderate

(vii) Construct a function that returns the average attendance of all staff over the 14 days according to the department. 

In [58]:
# WRITE YOUR CODE HERE

def avg_att_dep(array):
    average_attendance = []
    average_finance = []
    average_staffing = []
    j = 0
    for i in array.total:
        if array.Department[j] == 'FINANCE':
            average_finance.append(i)
        else:
            average_staffing.append(i)
        j = j + 1
            
    average_attendance = [sum(average_finance)/len(average_finance), sum(average_staffing)/len(average_staffing)]
    return average_attendance

print(emp_attendance.Department[2] == 'FINANCE')
average = avg_att_dep(emp_attendance)
final = pd.DataFrame(average, index = ['FINANCE', 'STAFFING'], columns = ["Average Attendance"])
final

True


Average Attendance
FINANCE                 10.6
STAFFING                10.5